### ISSUE TITLE
No footer background in Chrome

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/dougfir-pelican-theme#25]
Issues have been created in osuosl-pelican and cass-pelican repos:

https://github.com/osuosl/osuosl-pelican/issues/38
https://github.com/osuosl/cass-pelican/issues/5

but the issue needs to be fixed here.

Thanks to @shivamMG for finding the issue.

**Comment by shivamMg** [comment]
@matthewrsj I have submitted a fix https://github.com/osuosl/dougfir-pelican-theme/pull/26. You can ping me if there is some problem. One thing, when I compiled `main.scss`, it had some some changes that were not in `main.css`. I have included the changes in both the files for now.

**Comment by matthewrsj** [comment]
Fixed by #26
