### ISSUE TITLE
sync main.scss with main.css

### ISSUE THREAD

**Issue by Kennric** [osuosl/dougfir-pelican-theme#37]
When making css changes, we should be editing the scss file and compiling it to main.css. I know of at least one change that was made to the css and not scss, and I suspect there are many others. 

We need to generate css from main.scss, compare to the existing css, and sync any changes, then only use scss in future.

As a part of this process, it would be nice to pull common colors and other attributes into scss variables. 

@subnomo @leian7 @alxngyn @athai 

see: http://sass-lang.com
and http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html

**Comment by subnomo** [comment]
This was closed by #40.
