### ISSUE TITLE
Browser inconsistencies

### ISSUE THREAD

**Issue by subnomo** [osuosl/dougfir-pelican-theme#41]
There are a few inconsistencies between browsers:
- The top bar has a gradient in Firefox but not in Chrome or Opera.
- The search button is orange only in FF.
- Only half of the hamburger menu icon that appears as you shrink the window sideways is highlighted when you click/mouse over it in Chrome/Chromium.

**Comment by kelnera** [comment]
Does anyone know how to fix this or what the timeline would be? I'd like to
have some information if they ask about it...but only if they ask about it.
If not, I can just conveniently forget it's an issue.

**Comment by subnomo** [comment]
@kelnera I'll take a look, I can probably fix this tomorrow.

**Comment by kelnera** [comment]
@subnomo Great, thanks! Keep me posted.
